# Generated by Django 3.2 on 2021-04-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perioddetails',
            name='user',
        ),
    ]
