# Generated by Django 3.2 on 2021-04-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0001_initial'),
        ('dashboard', '0002_remove_perioddetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perioddetails',
            name='period_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.period'),
        ),
    ]
